imports:
    - { resource: config.yml }

#framework:
#    test: ~
#    session:
#        storage_id: session.storage.mock_file
#    profiler:
#        collect: false

framework:
    test: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing_test.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
#    templating:
#        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    session:
        storage_id: session.storage.mock_file
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  ~
#        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    profiler:
            collect: false


security:
    encoders:
        AppBundle\Entity\AppUser: plaintext

    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

doctrine:
    dbal:
        driver:   pdo_sqlite

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
