# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\AppUser: bcrypt

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        oauth_token:                                   # Everyone can access the access token URL.
            pattern: ^/oauth/v2/token
            security: false

        api-public:
            pattern: ^/api/v1/register-user
            security: false

#        api:
#            pattern: ^/api/v1                          # All URLs are protected
#            fos_oauth: true                            # OAuth2 protected resource
#            stateless: true                            # Do no set session cookies
#            anonymous: false
#            provider: fos_userbundle

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            pattern: ^/
            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                #csrf_provider: security.csrf.token_manager
            logout:     true
            anonymous:  true
            logout_on_user_change: true
